<?php

$site_ga_code = Mage::getStoreConfig(Wsu_WebmasterTools_Helper_Data::XML_PATH_SITEGACODE);
$googlesiteverifi = Mage::getStoreConfig(Wsu_WebmasterTools_Helper_Data::XML_PATH_GAVERIFI);
$msvalidate = Mage::getStoreConfig(Wsu_WebmasterTools_Helper_Data::XML_PATH_MSVALIDATE);

$fb_admin = Mage::getStoreConfig(Wsu_WebmasterTools_Helper_Data::XML_PATH_FBADMIN);

$links = false;
$versioning = "1.4.11-37384-0.6.2";


$jtrackversion = Mage::getStoreConfig('wsu_webmastertools/analytics/jtrackversion');

$url = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB);
$url_parts = parse_url($url);
$site_base_url = $url_parts["host"];

$cookie_store_base_url = ".".$site_base_url;
$prefix = '.dev.';
if (substr($cookie_store_base_url, 0, strlen($prefix)) == $prefix) {
    $cookie_store_base_url = substr($cookie_store_base_url, strlen($prefix));
} 



$campus = Mage::getStoreConfig('wsu_webmastertools/analytics/analytics_campus');
$college = Mage::getStoreConfig('wsu_webmastertools/analytics/analytics_college');
$unit_type = Mage::getStoreConfig('wsu_webmastertools/analytics/analytics_unittypes');
$unit = Mage::getStoreConfig('wsu_webmastertools/analytics/analytics_units');
$subunit = Mage::getStoreConfig('wsu_webmastertools/analytics/analytics_subunits');

$is_editor = "false";

$server_protocol = "HTTP\/2.0";
$view_type = "FrontEnd";

$site_ga_code = "" !== $site_ga_code ? $site_ga_code : "false";
// will be to a helper file which would return an object

$help = Mage::helper('wsu_webmastertools');
$ec = $help->getEcObject();



?>


<?php if ($googlesiteverifi!=""): ?><meta name="google-site-verification" content="<?=$googlesiteverifi?>" /><?php endif; ?><!--J5p8Yx8Li1yaN41fhtvl1zzJVoApq1t67l1WdFNff4c-->
<?php if ($msvalidate!=""): ?><meta name="msvalidate.01" content="<?=$msvalidate?>" /><?php endif; ?>

<?php if ($fb_admin!=""):
		$fb_og_image = Mage::getStoreConfig(Wsu_WebmasterTools_Helper_Data::XML_PATH_FBOG_IMAGE);
		$fb_og_site_name = Mage::getStoreConfig(Wsu_WebmasterTools_Helper_Data::XML_PATH_FBOG_SITENAME);
		$fb_type = Mage::getStoreConfig(Wsu_WebmasterTools_Helper_Data::XML_PATH_FBOG_TYPE);
		
		$this->loadLayout();
		$title=htmlspecialchars($this->getLayout()->getBlock('head')->getTitle());
		$description=htmlspecialchars($this->getLayout()->getBlock('head')->getDescription());
 ?>
    <meta property="og:title" content="<?=$title?>" />
    <meta property="og:type" content="<?=$fb_type?>" />
    <meta property="og:url" content="<?=$url?>" />
    <meta property="og:image" content="<?=$fb_og_image?>" />
    <meta property="og:site_name" content="<?=$fb_og_site_name?>" />
    <meta property="og:description" content="<?=$description?>" />
    <meta property="fb:admins" content="<?=$fb_admin?>" />

    <meta name="twitter:card" content="summary" />
    <meta name="twitter:description" content="<?=$description?>" />
    <meta name="twitter:title" content="<?=$title?>" />
    <meta name="twitter:image" content="<?=$fb_og_image?>" />

<?php endif; ?>


<?php if( false !== $links ):?>
    <link rel="prev" href="<?=$links["prevUrl"]?>" />
    <link rel="next" href="<?=$links["nextUrl"]?>" />
<?php endif;?>






<script type='text/javascript' src='//repo.wsu.edu/jtrack/<?=$jtrackversion?>/jtrack.min.js?ver=<?=$versioning?>'></script>
<script type='text/javascript'>
/* <![CDATA[ */
var wsu_analytics = {
        "defaults":{
            "cookieDomain":"<?=$cookie_store_base_url?>"
        },
        "wsuglobal":{
            "ga_code":"UA-55791317-1",
            "campus":"<?=$campus?>",
            "college":"<?=$college?>",
            "unit_type":"<?=$unit_type?>",
            "unit":"<?=$unit?>",
            "subunit":"<?=$subunit?>",
            "events":[]
        },
        "app":{
            "ga_code":"UA-69906812-3",
            "is_editor":"<?=$is_editor?>",
            "site_base_url":"<?=$site_base_url?>",
            "server_protocol":"<?=$server_protocol?>",
            "view_type":"<?=$view_type?>",
            "events":[]
        },
        "site":{
            "ga_code":"<?=$site_ga_code?>",
            "ec":<?=$ec?>,
            "events":[]
        }
    };
/* ]]> */
</script>
<script type='text/javascript' src='/js/wsu/analytics/default_events.js?ver=<?=$versioning?>'></script>
<script type='text/javascript' src='/js/wsu/analytics/default_ui-events.js?ver=<?=$versioning?>'></script>
<script type='text/javascript' src='/js/wsu/analytics/analytics.js?ver=<?=$versioning?>'></script>


