<?php

$site_ga_code = Mage::getStoreConfig(Wsu_WebmasterTools_Helper_Data::XML_PATH_SITEGACODE);
$googlesiteverifi = Mage::getStoreConfig(Wsu_WebmasterTools_Helper_Data::XML_PATH_GAVERIFI);
$msvalidate = Mage::getStoreConfig(Wsu_WebmasterTools_Helper_Data::XML_PATH_MSVALIDATE);

$fb_admin = Mage::getStoreConfig(Wsu_WebmasterTools_Helper_Data::XML_PATH_FBADMIN);

$links = false;
$versioning = "1.4.11-37384-0.6.2";


$jtrackversion = Mage::getStoreConfig('wsu_webmastertools/analytics/jtrackversion');
